language: node_js
node_js:
- '12'
cache:
  directories:
  - "$HOME/.npm"
install:
- npm ci
script:
- npm test
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_script:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find . ! -regex '^./build\(/.*\)?' ! -regex '^./.git\(/.*\)?' -delete
- mv -v ./build/* .
- rm build -r
- git push origin master
env:
  global:
    secure: qAJXAIfy3CiTvaJ2fwD9Q+UBvy5Gub52lFlFPEfFxPu0ioRzbXpqw/ipjAn/7jY7RyzA/nbJpdVFTgg9QKdIcBzEiRvsttjG7whnPvPBUSTuiHMDDOqTCY1PIzrOrsLCu90T3S9ji9fxWDy0BviLLaeOoK3zZiikhEo+DVembw+6nZpNFMi9B5O3zFNJLRUjDn6Dy2GgebffcyBg0xnfxltaO1CqANiC0NV6ifQ20u0pkH2QaD9HL+ic99gmKfik6y8Vq3mLXnsTsV6oB4IkxNBl4xYdcfL7HYzUlY5MSlNW4uE+saY078Mw6r1nCoDBcM52nyTAw5ifsTSjctSP/HWQhRSvHuOJgB+qGpBO+dTlGuSYvLl1gnBH0aBPtWSWGFqd8T/KrRRWu21A+WxxnwrhW7kleXC97LI9S4EHTjB+Xe+IVJ1MNANfeMVo2hh2gJoZJksuSWxO37NeZ8cRwlkS5CQiWnqmcr7lBm+CyhIICkD0GAQFzvWRTG8RxwS5aDzJLveulMShfc90KbD+ueGPKUUCGQvhJE3QnFY51fyz6A2+rXRJE9o2FDYgklyF9wWCVO8T5z1haoo0IuyXT+lbTu7Oe900sgvcEhTny31JGTb1w5OH+JGBJEJD9UI38si/i0A0yP96A3pvddvrEsNd5kpmIt/PTKvXSjW6Gwc=
