language: node_js
dist: xenial

node_js:
    - lts/*

before_install:
- npm install
- npm run update
- npm run build

after_install:
# - npm run dev

deploy:
    provider: script
    script: bash ./scripts/deploy.sh