language: node_js
node_js:
- '12'
install:
- npm ci
script:
- npm test
after_success:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find -maxdepth 1 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 2 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 3 -name node_modules -type d | xargs sudo rm -rf
- find ! -regex '^./build\(/.*\)?' -a ! -regex '^./.git\(/.*\)?' -a ! -regex '.' |
  xargs sudo rm -rf && sudo mv ./build/.* ./build/* . && sudo rm build -r
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_script:
- setup_git_user
- git add .
- git commit -m "Push from development branch at Travis"
- git push origin master
env:
  global:
    secure: g+v3OuHfjVWWOR1Vdlj+YxARS5FTqgM8xvvr/89rGMpMA1hFvc56osnqZdHyWc7qp08qck2aPc4rPkrz5JQU6ltLtXvamSp0Yd2z4Ee4h/J6We+lR58Uzt7iuxKaiaF2/lfkfezYr5u0NJGUy8iiFOPp4YukEcdukUy3lBaNdBNuP8WD+wgveOUTKE7CIq4IOZ5un5ppEJE8JxA7d3lIkykd84gAK0P72rmFH4hkrTVgM4dvN9Dq+dYniA6REDaBkuaY6FP2XbqFWO3+WbMW3g9M6TX5fdARr7sP1gClVAXJGsrLTW1YNFCO95tTeYAo9f/ulYQPdh1LPeC6T9momgJk19ZvZbA5ji96nSGYYlMoS6JG7strG0djaXEXp5YAG98qvvWe1/yFSfj57Wiczff1gzjFGoUQ4PhXCoh2eD9XiS31gKmGDzyR+alNAo1hRmgQzySdHZ291yFdlqjMz6hMdhMxlsOFXYdqOyJr/V93p83SpJweUAjcfPWSpxqVBG3QGmNB35AbtTOMxxE5wqAcdthnZ++Z/UHyg+ZNMN54Hl9O4NajOgK3RAH7sYWH9OXnwYowKw7svModWYnnQ0jIczahj/84GUnigNIPh4ASoRQ+xaXXAFkawBye1MJEL7ExeWt8xZ8unH3gNcNktBFOzaN4NgMPrJk1FASFRNQ=
