language: node_js
node_js:
- '12'
install:
- npm ci
script:
- npm test
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_script:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find -maxdepth 1 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 2 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 3 -name node_modules -type d | xargs sudo rm -rf
- find ! -regex '^./build\(/.*\)?' -a ! -regex '^./.git\(/.*\)?' -a ! -regex '.' |
  xargs sudo rm -rf
- mv ./build/* .
- mv ./build/.* .
- sudo rm build -r
- setup_git_user
- git add .
- git commit -m "Push from development branch at Travis"
- git push origin master
env:
  global:
    secure: BvTi0lh5eyirUShRfV/ufiMVIyvEcVaiJOTaOSkhp50hM6t4o5XTq/fB+AXEvhTebY8rPh4zeLFRRthgcJKXJ3BEm8KrRLOMVhvzUytFLhVXxzgWwdJJwl22o/Q2cf+y4WX4mKB9ITfg3dBYH95Z0gVaOJLgPIb2fCYG77yBkl1KdFOlTav7NqmT9mPxmYka0svLvnMlqLyeaBTn3XPY2wTWElZ4uZtita/yCkH14YgcfR98+/CLEkrtSgvE/dDCm9W8u8sqWDWZNs33/7PBeCMO8T9r+4Hr05c8OE1AAhQtCNJsQQxZGFi6bPAL90xtTXUSNNEV66Fayblk7XSkjzGv0aMCiiRfbPCKkbGRnhMrMoKnTH/SghPfUU1xevxrMPT8wNXHrwbLp/iaAezrsmwFhvNM3fx6Y47mlR6l/D1NnIVkIsjIYr3mtLjV68rGdb7WM7X21QnTUPvJCq/MC28ZD7CjP6+RIyCHecYYOrvLe+4PO/xXib9jlxWr7qdvuHFLQA8lXCmpRmvvemwMmw04MjPbvWKxK7qoYbxq5ahC+nmfmwepKGRozKMyy0GTZS40RrXy370i3vFchbEmiXbDtRgAo+ubpEMjb3rwkge4dfUK6RXrP6G4D5VNcxYjYRmR30WHWyILWttNuFH06ZqyrShy0mlfTdPaCJoVb38=
