language: node_js
node_js:
- '12'
install:
- npm ci
script:
- npm test
after_success:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find -maxdepth 1 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 2 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 3 -name node_modules -type d | xargs sudo rm -rf
- find ! -regex '^./build\(/.*\)?' -a ! -regex '^./.git\(/.*\)?' -a ! -regex '.' |
  xargs sudo rm -rf
- xarg_child_pids=`pgrep -P $!`
- wait $xarg_child_pids
- sudo mv ./build/.* ./build/* .
- sudo rm build -r
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_script:
- setup_git_user
- git add .
- git commit -m "Push from development branch at Travis"
- git push origin master
env:
  global:
    secure: C7eH1hxxG9ZHZnxEJwFKTOJAcgfUiqTCbv6uonUmTSTlRE7j8E13vHWpqEOXJ8UKsDuqU+r8ytG6gcRaXvJdZuaolt58snUt3Gt+aiXSzB3iMh95N8k2AXkTLbfaT+NzFv7g/zqmwjK3k9IhLMYcrCEPpWi3v99q0HRLA+ESqX3GQ8dTBBO5wv/VbcHrIYbliteUAyYCxGq+ZrL4dT99ceer2H8I8NavVZXdodkHYrSzFfw5Vq8rBPQMWY/6trXKQ3yonnFCe0UXM4h4rQ4ETEBgERiHuZpR1+GHdZU4uo6xw0EyUPJaya4Ig+sT+kNgykDP2gEkueQGcarweTu4dQixUpuG272gdpjJI50OxrIIQzAvDgefVV4F+IP8gFemO78dmZLqWJUs1feTr802Ajbntm8eMnPn7mTvJBd6yknLMN6EvP8E5p9DSSqBGLLnP12/zT5qi4pJQpzJvXlvp+EolnoQb7VTtZto/4WLqDXovqAtP7cTSX1Cohbx4R//kbkcyT+c2ohzANC7BRSkNJDxA/YBSVbkev03Ro4sGPWhkhfCyOTnrF3WknOUUdm0wAygblRAgp2xQMF54nvBo1XNGz7yeH4AGx5leH7uLE1GLnVfqMJKfbEPNi7JYOl8I5V+/wCv1iUWDZ8cczFWYOp0+lrQeKYYKM+SPWtEGRs=
