language: node_js
dist: xenial

node_js:
    - lts/*

before_install:
- npm install
- npm run update
- npm run build

after_install:
# - npm run dev

deploy:
# deploy master to production
 - provider: script
   script: bash scripts/deploy.sh production
   skip_cleanup: true
   github_token: $github_token
   local_dir: build
   on:
     branch: master