language: node_js
node_js:
- '12'
install:
- npm ci
script:
- npm test
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find -maxdepth 1 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 2 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 3 -name node_modules -type d | xargs sudo rm -rf
- find ! -regex '^./build\(/.*\)?' -a ! -regex '^./.git\(/.*\)?' -a ! -regex '.' |
  xargs sudo rm -rf
- sudo mv ./build/* .
- sudo mv ./build/.* .
- sudo rm build -r
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_script:
- setup_git_user
- git add .
- git commit -m "Push from development branch at Travis"
- git push origin master
env:
  global:
    secure: JxOoA1zqu0Jq43mDbrjgcMNQ1BGTpLG4DQ7ezemM34e68iH7mt+ZDvNH8Lu/PHRuVpr06Y8ifmcsMMBgRV667fbTOeTri79eprv57nNrqm67rINCRWHoCmisiPaRBwjiuBK1qNMHWyWqq1//na8nQxujNXW9xYa/fha/fA/0eDY6mNkrRYRDG9n++H1tssncGbkBEceezZJmgzpWgzSVblTTGHvazpGWia4KUIb6Fg3lXqpiWPsqhiCic9IUsTGiILf+jNUY3L+bH0Yq/p4xI+g6U1OOYMk9tkg4NdL4Pt0iWL1jrQFhBp5nzyMGXxnEeBh9U9nVKJ2RNwImio27cYMZW1lnRkIHSJuvOCqsPMk8RhqH5K2uenDOXUUIyfuJD4d1DEBfFaDC352ckbzLBS6M3Bg/0++DDth2vwJ/XXWrTFBLrnqrV3Y7KexykJTPR5qCAGyJzCXIq0b/ylWSkJfqxm8ynmgwCK6x20JEARQG5b3tzzOZdTcRwQek872Gbzuvf6TTVsTR8pL5smphjwFEvQX55gJzCFcyOpdWnnXVnGh2a8ZgQjvwXFx39wHQhLqGMVNQ0tBiRxGygWDS/4mcqhrQOpsC7t60ky6mGkfuZxw8rtUjwP61fpHysNl8OBT31aHr8YDTaRY2DNk/Yi7Omg8Nyve3vVl0vRmP1rQ=
