language: node_js
node_js:
- '12'
cache:
  directories:
  - "$HOME/.npm"
install:
- npm ci
script:
- npm test
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:MachineAtKrypton@github.com" > .git/credentials
after_script:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find . ! -regex '^./build\(/.*\)?' ! -regex '^./.git\(/.*\)?' -delete
- mv -v ./build/* .
- rm build -r
- git add .
- git commit -m "Travis push from development branch"
- git push origin master
env:
  global:
    secure: MS0kmmxDUGgTN1DU6SgLCgmCVrUDM78likLvl3al5i5DZqM7jCCRyswB038Cc7WslhMHy3ghS0y+ChqL3xYwCViiBU8/qMoHYM0G1gJsyvuKY/O3m5U3OyWmjO05PDEWG55aCkyeKTmRfW3shszAR0ZodpPmxxbf+HUc970Ps2NdX+Da5KnyYc7MuQ0zEp1rzIpweeKB3Di+u6junKl2fEqgWA3kfNCCnWQ4a2U+QOdwEzqQwGrPhb/rsIvCLXL/H15yLo673wQqsARBIdAiwWRIzPZza99Ff0dWISMFrz2jNTY6/tWTzu03kbehr3dLdAxcxqeIoye+taDNYoEhUq7WbY/ZjFuM0QB6NCxioXRPed6MhIhaWtBAkD7hQwgDlyukbtjlE5VGPksOjOnfBVrhN/nQE6/5Hs2SHLa2L3IEFpNndQEYUZr/wT8amI+Fpn5fHae5SezyuV4CgRuoujxQXk7GzbKq0jYI6KaOntuPht5KZGxXTj0JgNFkpqVXx9uowJPAL9e8fuju/x8j90MUmwx1iTyoqvz3W4UAOMBP6s+pLTnMumvX2wOS1N1PCl49RsmjNdeotavElpNwJ1XHbFWtRnp/BUDP1fHC5y0xQ0FSVNpVr270V2Y7sXrocBYnppOIFYzqfvSsQzev1vp7b4hwvyPLvXfgSW7Q0Ng=
