language: node_js
dist: xenial

node_js:
    - lts/*

before_install:
- npm install
- npm run build

after_install:
# - npm run dev

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # # This generates a `web` directory containing the website.
    # make web
    # cd web
    git init
    git checkout -b production
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://krypton-unite:$GITHUB_API_KEY@github.com/krypton-uniteproduction master &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi