language: node_js
node_js:
  - '12'

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

script:
  - npm test

-after_success:
  - . ./scripts/create_all_branches.sh
  - create_all_branches
  - git checkout master
  # Remove all but build folder
  - find . ! -regex '^./build\(/.*\)?' ! -regex '^./.git\(/.*\)?' -delete
  # Move build contents to root folder.
  - mv -v ./build/* .
  # Delete build folder
  - rm build -r
  # Deploy to master branch
  - git push origin master