language: node_js
node_js:
- '12'
cache:
  directories:
  - "$HOME/.npm"
install:
- npm ci
script:
- npm test
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:MachineAtKrypton@github.com" > .git/credentials
after_script:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find . ! -regex '^./build\(/.*\)?' ! -regex '^./.git\(/.*\)?' -delete
- mv -v ./build/* .
- rm build -r
- git add .
- git commit -m "Travis push from development branch"
- git push origin master
env:
  global:
    secure: DKaybYb9Uezp9bvd2NEqi72ih2raGp39gkdnmQbz704nFp35y0qEH/dGW0CNfDzdECweZhEW4hS9FMF+DzeKrgJq8zTodyQ9oEvdJ9TjBU0oZUL6npA3RKjDtQS0CVFAVcduoDJSl0frJnYpUth8XMd1VQEhr++/245w+rQFs2SY+6mVk50aN4pifbz3DMLiYEQo4oO3e1POEqFxBFGfZsSNo0etLNzXiXxgq9NKOHGwm1VdGIQW1tDh7Y8GjOtN/J5EFBfm/RSlM5QY8N14fZmTuThA2+3aDU0JQbXtxYa1PVXjBydhftsHdx5bTgqotJ6qEjlVl8Fo80o5xGtqBawip0QkaKIPZTjRjnbg0COqobPnqIFBP95J/VHJvAIcB8zQ4AKvk0hjAzOPbYKPAxGDPmfKboBOVpp5y0ups9Z6NwPNH7ZfuJoJNtabuJ0rBO/Qn8nJT5elLBtl8qXS2YF2hP44REUiZblDA3Vvd9Oe5SWmuw1+7/4+iNYdbciLela3clDC+/s79ZQsoRrV4uWX6QH8lE/5GnIik1VSvz7+0awCCdH/hPH8jtNERLgK/PVpiOZRJ8EkZRKGKWez7WboOfxTk0WW7FChK/MNWMDNbkipiE1jOx4RyVWwt/L774u9EySz9aMIZUN2ydOnZUf9TaVdRzgfAguwDQsVplM=
