language: node_js
node_js:
- '12'
install:
- npm ci
script:
- npm test
after_success:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- find -maxdepth 1 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 2 -name node_modules -type d | xargs sudo rm -rf
- find -maxdepth 3 -name node_modules -type d | xargs sudo rm -rf
- find ! -regex '^./build\(/.*\)?' -a ! -regex '^./.git\(/.*\)?' -a ! -regex '.' |
  xargs sudo rm -rf
- xarg_child_pids=`pgrep -P $!`
- echo $xarg_child_pids
- wait $xarg_child_pids
- sudo mv ./build/.* ./build/* .
- sudo rm build -r
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_script:
- setup_git_user
- git add .
- git commit -m "Push from development branch at Travis"
- git push origin master
env:
  global:
    secure: S6M9Qp43DeEF7KTeiuShiN30X75dc8AbAgMd8QysdpgjIrOx83PjWnkC3jjadWl0PNSWyoLlM6ZL/HnB1EhrUPXyOC0HWMxs70x4doEEUiv6Y7Eab6/kSz5qOTMMal25KllSVaqCRfqiNYHpZbKQTKaDKObKtIRIwf1nf+pdlrrS3d9BrMdU52BW2c/m3OwAV5VzKSji01OlWniJIrRQ0WdF6kC1AXRUbGFGMHvY8z3ksn8WDFQk4d1IL5d/SKxcjc17vs2VwtNR9dCZX+dsNC/BGXal4vV+MX09SWYVttJRZL1umsNQLwejkXTnR5LEAb50pC3+WlUnynMqXHZfyn/dDGl2GlgaQ0ZTXseN2x6f/qdbc2krqqHRCLQAmdjy/OvLYh9Qo6X4S47p0fi8T96vrEO4qs4Hb91iFLA5W9N4x+2yev6NYmBIn/1GM6btn9HTN2vBecZfHaTy/lXd5NU9U1l0z+uI9X1ZAzMYkMJlvZFnaaqvYVtd8sPRNjZINGGSIUc2f1HbgDAEWwgZJPwN68Aoy8IiuC1JCQM+QZDLiK3cma99w8uY/4EILaySLVMYxcadX7p3T7d6g5nG+a0aTZIbh3TKVid59Rki09/AeFBFnoppVntLf8jwvXvI01eM09XLZWjI9815PjmFr26Gc0lb7ZVkTcyp2zzy6pc=
