language: node_js
node_js:
- '12'
install:
- npm ci
script:
- npm test
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_script:
- source ./scripts/create_all_branches.sh
- create_all_branches
- git checkout master
- sudo find . ! -regex '^./build\(/.*\)?' -a ! -regex '^./.git\(/.*\)?' -o -regex
  '^./build/studio/dist\(/.*\)?' -o -regex '^./build/web/out\(/.*\)?' -o -name node_modules
  -type d | xargs sudo rm -rf
- sudo mv -v ./build/* ./build/.* .
- sudo rm ./build -r
- setup_git_user
- git add .
- git commit -m "Push from development branch at Travis"
- git push origin master
env:
  global:
    secure: TawgMttI4OnkajanFYxCa1Nzl2pIUAmyrKU5n0REq6THD12wPwfgiFdP9TxA+Yltt+Bqy8OJsIEIcqgk1Sjzt+QlT4Tx3urQyu4GT6u8++iIO6i5qJ32g6yJW5Qx5IJOhF1adadkGSFyVYr2GU3M76LQWIsHLB0gFIv0nGCw3KiUT3tkfKKXl9oi3CKORk42NSs6Xa0pUyByEolyCH0p9hOn0+JaY02QYZnKKEL7wPTM6CidDb94iB7CK2xZgqOKOlPr+ghG+j4GyETE7hY22tXpCo5gd0lMUVrPbMIzOkD2I3AzVSuh1En+T1gmpwxHot8ioy0K7Y9xN1lLH/v+Q9Gm6C4iLnPkyOQVmQaRH76NwX3cGHqExXTXJnLOE2Mqghca/7rUnNHJkmLC6JQGpTfvbSr/e4Fuvbu7srv6c38ZvKhKFh5Ys2h0I6IcAFADtkzk2Qx93U30YcM0UamdDXCjobZAqpA5grDurqsG28g5hZXGfG8snB0JamkIUwSm7TcC40Cm94hYQV+0ee7drUFWgVjkMpIjJQErmiMRXAatUNhRtbAmZ+ICCM0AcrDavSlzl5scPQWKRYZPsLhG/YSDJsYC+hbv8M6yl3KQpNx5l807i/wqceMMdW6FQdNAhVjWVeifwKX76bTgm9DL2pr+7iSF22P+gjbc2K1xWqM=
